--[[
TODO:
- Operation:
    - map_mirrors: test
    - process: test
    - update_references: implement
    - file_is_dir_file: test
    - dir_file: test
    - evaluate: test
    - applies: test
- FileToMarkOperation:
    - map_mirrors: test
    - process: test
    - update_references: implement
- DirOperation:
    - map_a_to_b: test (might already be done in `Inferrer`)
    - case:
        - to_files:
            - map_a_to_b: text
- MarkOperation:
    - process: test
]]
