local Path = require("hl.path")
local Goals = require("htl.goals")
local Config = require("htl.config")

describe("get_path", function()
    it("gets", function()
        local expected = Path.joinpath(Config.get("goals").dir, os.date("%Y%m") .. ".md")
        assert.are.same(expected, Goals())
    end)
end)
